// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// stable_col_means_cpp
arma::vec stable_col_means_cpp(const arma::mat& x);
RcppExport SEXP _relieverChangepoint_stable_col_means_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(stable_col_means_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// nmcd_individual_loss
arma::vec nmcd_individual_loss(const arma::vec& x, int l, int r, int l_end, int r_end, const arma::vec& sorted_reference, int tail_truncation);
RcppExport SEXP _relieverChangepoint_nmcd_individual_loss(SEXP xSEXP, SEXP lSEXP, SEXP rSEXP, SEXP l_endSEXP, SEXP r_endSEXP, SEXP sorted_referenceSEXP, SEXP tail_truncationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type l(lSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type l_end(l_endSEXP);
    Rcpp::traits::input_parameter< int >::type r_end(r_endSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sorted_reference(sorted_referenceSEXP);
    Rcpp::traits::input_parameter< int >::type tail_truncation(tail_truncationSEXP);
    rcpp_result_gen = Rcpp::wrap(nmcd_individual_loss(x, l, r, l_end, r_end, sorted_reference, tail_truncation));
    return rcpp_result_gen;
END_RCPP
}
// exact2relief_itv_routine_c
arma::ivec exact2relief_itv_routine_c(const int& l, const int& r, const arma::ivec& miss_cover_len, const arma::ivec& int_len, const arma::ivec& layer_point, const arma::imat& int_eps);
RcppExport SEXP _relieverChangepoint_exact2relief_itv_routine_c(SEXP lSEXP, SEXP rSEXP, SEXP miss_cover_lenSEXP, SEXP int_lenSEXP, SEXP layer_pointSEXP, SEXP int_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type l(lSEXP);
    Rcpp::traits::input_parameter< const int& >::type r(rSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type miss_cover_len(miss_cover_lenSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type int_len(int_lenSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type layer_point(layer_pointSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type int_eps(int_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(exact2relief_itv_routine_c(l, r, miss_cover_len, int_len, layer_point, int_eps));
    return rcpp_result_gen;
END_RCPP
}
// relief2exact_itv_routine_c
arma::imat relief2exact_itv_routine_c(const int& id, const arma::ivec& int_len, const arma::ivec& layer_point, const arma::imat& int_eps, const int& n);
RcppExport SEXP _relieverChangepoint_relief2exact_itv_routine_c(SEXP idSEXP, SEXP int_lenSEXP, SEXP layer_pointSEXP, SEXP int_epsSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type id(idSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type int_len(int_lenSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type layer_point(layer_pointSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type int_eps(int_epsSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(relief2exact_itv_routine_c(id, int_len, layer_point, int_eps, n));
    return rcpp_result_gen;
END_RCPP
}
// cpd_r_by_loss_block
List cpd_r_by_loss_block(const std::string& method, const int& n, const int& L, const int& dm, const arma::imat& search_intervals, const arma::vec& pen_val, const double& prune_value, const arma::ivec& run_loss_outputs, Rcpp::Function& reg_fun_wrap, const arma::ivec& miss_cover_len, const arma::ivec& int_len, const arma::ivec& layer_point, const arma::imat& int_eps, Rcpp::Nullable<Rcpp::List> cache_state, bool return_cache_profile, bool use_owner_key);
RcppExport SEXP _relieverChangepoint_cpd_r_by_loss_block(SEXP methodSEXP, SEXP nSEXP, SEXP LSEXP, SEXP dmSEXP, SEXP search_intervalsSEXP, SEXP pen_valSEXP, SEXP prune_valueSEXP, SEXP run_loss_outputsSEXP, SEXP reg_fun_wrapSEXP, SEXP miss_cover_lenSEXP, SEXP int_lenSEXP, SEXP layer_pointSEXP, SEXP int_epsSEXP, SEXP cache_stateSEXP, SEXP return_cache_profileSEXP, SEXP use_owner_keySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const int& >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type search_intervals(search_intervalsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pen_val(pen_valSEXP);
    Rcpp::traits::input_parameter< const double& >::type prune_value(prune_valueSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type run_loss_outputs(run_loss_outputsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function& >::type reg_fun_wrap(reg_fun_wrapSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type miss_cover_len(miss_cover_lenSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type int_len(int_lenSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type layer_point(layer_pointSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type int_eps(int_epsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type cache_state(cache_stateSEXP);
    Rcpp::traits::input_parameter< bool >::type return_cache_profile(return_cache_profileSEXP);
    Rcpp::traits::input_parameter< bool >::type use_owner_key(use_owner_keySEXP);
    rcpp_result_gen = Rcpp::wrap(cpd_r_by_loss_block(method, n, L, dm, search_intervals, pen_val, prune_value, run_loss_outputs, reg_fun_wrap, miss_cover_len, int_len, layer_point, int_eps, cache_state, return_cache_profile, use_owner_key));
    return rcpp_result_gen;
END_RCPP
}
// cpd_mean_by_loss_block_cpp
List cpd_mean_by_loss_block_cpp(const std::string& method, const int& n, const int& L, const int& dm, const arma::imat& search_intervals, const arma::vec& pen_val, const double& prune_value, const arma::mat& data, const double& ratio, const arma::ivec& miss_cover_len, const arma::ivec& int_len, const arma::ivec& layer_point, const arma::imat& int_eps, bool return_cache_profile, bool use_owner_key);
RcppExport SEXP _relieverChangepoint_cpd_mean_by_loss_block_cpp(SEXP methodSEXP, SEXP nSEXP, SEXP LSEXP, SEXP dmSEXP, SEXP search_intervalsSEXP, SEXP pen_valSEXP, SEXP prune_valueSEXP, SEXP dataSEXP, SEXP ratioSEXP, SEXP miss_cover_lenSEXP, SEXP int_lenSEXP, SEXP layer_pointSEXP, SEXP int_epsSEXP, SEXP return_cache_profileSEXP, SEXP use_owner_keySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const int& >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type search_intervals(search_intervalsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pen_val(pen_valSEXP);
    Rcpp::traits::input_parameter< const double& >::type prune_value(prune_valueSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const double& >::type ratio(ratioSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type miss_cover_len(miss_cover_lenSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type int_len(int_lenSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type layer_point(layer_pointSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type int_eps(int_epsSEXP);
    Rcpp::traits::input_parameter< bool >::type return_cache_profile(return_cache_profileSEXP);
    Rcpp::traits::input_parameter< bool >::type use_owner_key(use_owner_keySEXP);
    rcpp_result_gen = Rcpp::wrap(cpd_mean_by_loss_block_cpp(method, n, L, dm, search_intervals, pen_val, prune_value, data, ratio, miss_cover_len, int_len, layer_point, int_eps, return_cache_profile, use_owner_key));
    return rcpp_result_gen;
END_RCPP
}
// cpd_r_by_cost_mat
List cpd_r_by_cost_mat(const std::string& method, const int& n, const int& L, const int& dm, const arma::imat& search_intervals, const arma::vec& pen_val, const double& prune_value, const arma::ivec& run_loss_outputs, arma::mat& cost_mat, Rcpp::Function& reg_fun_wrap, const arma::ivec& miss_cover_len, const arma::ivec& int_len, const arma::ivec& layer_point, const arma::imat& int_eps, bool is_full);
RcppExport SEXP _relieverChangepoint_cpd_r_by_cost_mat(SEXP methodSEXP, SEXP nSEXP, SEXP LSEXP, SEXP dmSEXP, SEXP search_intervalsSEXP, SEXP pen_valSEXP, SEXP prune_valueSEXP, SEXP run_loss_outputsSEXP, SEXP cost_matSEXP, SEXP reg_fun_wrapSEXP, SEXP miss_cover_lenSEXP, SEXP int_lenSEXP, SEXP layer_pointSEXP, SEXP int_epsSEXP, SEXP is_fullSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const int& >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type search_intervals(search_intervalsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pen_val(pen_valSEXP);
    Rcpp::traits::input_parameter< const double& >::type prune_value(prune_valueSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type run_loss_outputs(run_loss_outputsSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type cost_mat(cost_matSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function& >::type reg_fun_wrap(reg_fun_wrapSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type miss_cover_len(miss_cover_lenSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type int_len(int_lenSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type layer_point(layer_pointSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type int_eps(int_epsSEXP);
    Rcpp::traits::input_parameter< bool >::type is_full(is_fullSEXP);
    rcpp_result_gen = Rcpp::wrap(cpd_r_by_cost_mat(method, n, L, dm, search_intervals, pen_val, prune_value, run_loss_outputs, cost_mat, reg_fun_wrap, miss_cover_len, int_len, layer_point, int_eps, is_full));
    return rcpp_result_gen;
END_RCPP
}
// cpd_mean_by_cost_mat_cpp
List cpd_mean_by_cost_mat_cpp(const std::string& method, const int& n, const int& L, const int& dm, const arma::imat& search_intervals, const arma::vec& pen_val, const double& prune_value, const arma::mat& data, arma::mat& cost_mat, const double& ratio, const arma::ivec& miss_cover_len, const arma::ivec& int_len, const arma::ivec& layer_point, const arma::imat& int_eps, bool is_full);
RcppExport SEXP _relieverChangepoint_cpd_mean_by_cost_mat_cpp(SEXP methodSEXP, SEXP nSEXP, SEXP LSEXP, SEXP dmSEXP, SEXP search_intervalsSEXP, SEXP pen_valSEXP, SEXP prune_valueSEXP, SEXP dataSEXP, SEXP cost_matSEXP, SEXP ratioSEXP, SEXP miss_cover_lenSEXP, SEXP int_lenSEXP, SEXP layer_pointSEXP, SEXP int_epsSEXP, SEXP is_fullSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const int& >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type search_intervals(search_intervalsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pen_val(pen_valSEXP);
    Rcpp::traits::input_parameter< const double& >::type prune_value(prune_valueSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type cost_mat(cost_matSEXP);
    Rcpp::traits::input_parameter< const double& >::type ratio(ratioSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type miss_cover_len(miss_cover_lenSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type int_len(int_lenSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type layer_point(layer_pointSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type int_eps(int_epsSEXP);
    Rcpp::traits::input_parameter< bool >::type is_full(is_fullSEXP);
    rcpp_result_gen = Rcpp::wrap(cpd_mean_by_cost_mat_cpp(method, n, L, dm, search_intervals, pen_val, prune_value, data, cost_mat, ratio, miss_cover_len, int_len, layer_point, int_eps, is_full));
    return rcpp_result_gen;
END_RCPP
}
// wbs_r_twostep_loss_outputs
Rcpp::List wbs_r_twostep_loss_outputs(const int& n, const int& L, const int& dm, const arma::imat& lr_m, const arma::ivec& run_loss_outputs, Rcpp::Function& individual_loss_fun, const int& n_loss_outputs, const arma::vec& init_cand, bool recursive);
RcppExport SEXP _relieverChangepoint_wbs_r_twostep_loss_outputs(SEXP nSEXP, SEXP LSEXP, SEXP dmSEXP, SEXP lr_mSEXP, SEXP run_loss_outputsSEXP, SEXP individual_loss_funSEXP, SEXP n_loss_outputsSEXP, SEXP init_candSEXP, SEXP recursiveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const int& >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type lr_m(lr_mSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type run_loss_outputs(run_loss_outputsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function& >::type individual_loss_fun(individual_loss_funSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_loss_outputs(n_loss_outputsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type init_cand(init_candSEXP);
    Rcpp::traits::input_parameter< bool >::type recursive(recursiveSEXP);
    rcpp_result_gen = Rcpp::wrap(wbs_r_twostep_loss_outputs(n, L, dm, lr_m, run_loss_outputs, individual_loss_fun, n_loss_outputs, init_cand, recursive));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_relieverChangepoint_stable_col_means_cpp", (DL_FUNC) &_relieverChangepoint_stable_col_means_cpp, 1},
    {"_relieverChangepoint_nmcd_individual_loss", (DL_FUNC) &_relieverChangepoint_nmcd_individual_loss, 7},
    {"_relieverChangepoint_exact2relief_itv_routine_c", (DL_FUNC) &_relieverChangepoint_exact2relief_itv_routine_c, 6},
    {"_relieverChangepoint_relief2exact_itv_routine_c", (DL_FUNC) &_relieverChangepoint_relief2exact_itv_routine_c, 5},
    {"_relieverChangepoint_cpd_r_by_loss_block", (DL_FUNC) &_relieverChangepoint_cpd_r_by_loss_block, 16},
    {"_relieverChangepoint_cpd_mean_by_loss_block_cpp", (DL_FUNC) &_relieverChangepoint_cpd_mean_by_loss_block_cpp, 15},
    {"_relieverChangepoint_cpd_r_by_cost_mat", (DL_FUNC) &_relieverChangepoint_cpd_r_by_cost_mat, 15},
    {"_relieverChangepoint_cpd_mean_by_cost_mat_cpp", (DL_FUNC) &_relieverChangepoint_cpd_mean_by_cost_mat_cpp, 15},
    {"_relieverChangepoint_wbs_r_twostep_loss_outputs", (DL_FUNC) &_relieverChangepoint_wbs_r_twostep_loss_outputs, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_relieverChangepoint(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
