# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stable_col_means_cpp <- function(x) {
    .Call(`_relieverChangepoint_stable_col_means_cpp`, x)
}

nmcd_individual_loss <- function(x, l, r, l_end, r_end, sorted_reference, tail_truncation) {
    .Call(`_relieverChangepoint_nmcd_individual_loss`, x, l, r, l_end, r_end, sorted_reference, tail_truncation)
}

exact2relief_itv_routine_c <- function(l, r, miss_cover_len, int_len, layer_point, int_eps) {
    .Call(`_relieverChangepoint_exact2relief_itv_routine_c`, l, r, miss_cover_len, int_len, layer_point, int_eps)
}

relief2exact_itv_routine_c <- function(id, int_len, layer_point, int_eps, n) {
    .Call(`_relieverChangepoint_relief2exact_itv_routine_c`, id, int_len, layer_point, int_eps, n)
}

#' R loss-function backend using the loss-block cache.
#' @noRd
cpd_r_by_loss_block <- function(method, n, L, dm, search_intervals, pen_val, prune_value, run_loss_outputs, reg_fun_wrap, miss_cover_len, int_len, layer_point, int_eps, cache_state = NULL, return_cache_profile = TRUE, use_owner_key = TRUE) {
    .Call(`_relieverChangepoint_cpd_r_by_loss_block`, method, n, L, dm, search_intervals, pen_val, prune_value, run_loss_outputs, reg_fun_wrap, miss_cover_len, int_len, layer_point, int_eps, cache_state, return_cache_profile, use_owner_key)
}

#' Native mean-loss backend using the loss-block cache.
#' @noRd
cpd_mean_by_loss_block_cpp <- function(method, n, L, dm, search_intervals, pen_val, prune_value, data, ratio, miss_cover_len, int_len, layer_point, int_eps, return_cache_profile = TRUE, use_owner_key = TRUE) {
    .Call(`_relieverChangepoint_cpd_mean_by_loss_block_cpp`, method, n, L, dm, search_intervals, pen_val, prune_value, data, ratio, miss_cover_len, int_len, layer_point, int_eps, return_cache_profile, use_owner_key)
}

#' R loss-function backend using the cost-matrix cache.
#' @noRd
cpd_r_by_cost_mat <- function(method, n, L, dm, search_intervals, pen_val, prune_value, run_loss_outputs, cost_mat, reg_fun_wrap, miss_cover_len, int_len, layer_point, int_eps, is_full = FALSE) {
    .Call(`_relieverChangepoint_cpd_r_by_cost_mat`, method, n, L, dm, search_intervals, pen_val, prune_value, run_loss_outputs, cost_mat, reg_fun_wrap, miss_cover_len, int_len, layer_point, int_eps, is_full)
}

#' Native mean-loss backend using the cost-matrix cache.
#' @noRd
cpd_mean_by_cost_mat_cpp <- function(method, n, L, dm, search_intervals, pen_val, prune_value, data, cost_mat, ratio, miss_cover_len, int_len, layer_point, int_eps, is_full = FALSE) {
    .Call(`_relieverChangepoint_cpd_mean_by_cost_mat_cpp`, method, n, L, dm, search_intervals, pen_val, prune_value, data, cost_mat, ratio, miss_cover_len, int_len, layer_point, int_eps, is_full)
}

#' Run WBS-family twostep search for a set of loss outputs.
#' @noRd
wbs_r_twostep_loss_outputs <- function(n, L, dm, lr_m, run_loss_outputs, individual_loss_fun, n_loss_outputs, init_cand, recursive = FALSE) {
    .Call(`_relieverChangepoint_wbs_r_twostep_loss_outputs`, n, L, dm, lr_m, run_loss_outputs, individual_loss_fun, n_loss_outputs, init_cand, recursive)
}

